name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dev-tools
      run: sudo apt-get install -y --no-install-recommends build-essential pkg-config libssl-dev
    - name: Install deps
      run: cargo install bpf-linker
    - name: Build ebpf
      run: cargo xtask build-ebpf
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
